apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/shrt-api-pod
patchesStrategicMerge:
- kind-shrt-api-patch.yaml
images:
- name: shrt-api-image
  newName: shrt-api-arm64
  newTag: "1.0"
