apiVersion: v1
kind: Namespace
metadata:
  name: shrt-api-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrt-api-pod
  namespace: shrt-api-system
spec:
  selector:
    matchLabels:
      app: shrt-api
  template:
    metadata:
      labels:
        app: shrt-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: shrt-api
          image: shrt-api-image
          ports:
            - name: shrt-api
              containerPort: 3000
            - name: shrt-api-debug
              containerPort: 4000
          readinessProbe:
            httpGet:
              path: /debug/readiness
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /debug/liveness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: shrt-api-service
  namespace: shrt-api-system
spec:
  type: ClusterIP
  selector:
    app: shrt-api
  ports:
    - name: shrt-api
      port: 3000
      targetPort: shrt-api
    - name: shrt-api-debug
      port: 4000
      targetPort: shrt-api-debug
