apiVersion: v1
kind: Namespace
metadata:
  name: shrt-api-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrt-api-pod
  namespace: shrt-api-system
spec:
  selector:
    matchLabels:
      app: shrt-api
  template:
    metadata:
      labels:
        app: shrt-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: shrt-api
          image: shrt-api-image
